/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.CityName;
import Business.CityNetwork;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.MenuItem;
import Business.Restaurant.Order;
import Business.Restaurant.OrderStatus;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anshitaverma
 */
public class DeliveryManMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryManMainJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private CityNetwork cityNetwork;
    private UserAccount userAccount;
    
    public DeliveryManMainJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, CityNetwork cityNetwork, UserAccount userAccount) {
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.cityNetwork = cityNetwork;
        this.userAccount = userAccount;
        initComponents();
        populateData();
    }

    private void populateData() {
        
        DefaultTableModel currentOrdersModel = (DefaultTableModel) currentOrdersjTable.getModel();
        currentOrdersModel.setRowCount(0);
        int currentOrdercount=0;
        
        DefaultTableModel delieveredOrdersModel = (DefaultTableModel) deliveredOrdersjTable.getModel();
        delieveredOrdersModel.setRowCount(0);
        int deliveredOrderCount=0;
        
        DeliveryMan deliveryMan = (DeliveryMan) userAccount;
        for(Order order:deliveryMan.getOrders()){
            if(order.getOrderStatus().name().equalsIgnoreCase(OrderStatus.Delivered.name())){
                deliveredOrderCount++;
                Object[] row = new Object[7];
                row[0] = deliveredOrderCount;
                row[1] = order.getOrderedBy().getName();
                row[2] = order.getCustomerInstructions();
                row[3] = order;
                row[4] = order.getOrderStatus().name();
                row[5] = order.getAssignedBy().getName();
                row[6] = order.getRestaurant().getRestaurantName();
                
                delieveredOrdersModel.addRow(row);
                        
            }else{
                currentOrdercount++;
                Object[] row = new Object[7];
                row[0] = currentOrdercount;
                row[1] = order.getOrderedBy().getName();
                row[2] = order.getCustomerInstructions();
                row[3] = order;
                row[4] = order.getOrderStatus().name();
                row[5] = order.getAssignedBy().getName();
                row[6] = order.getRestaurant().getRestaurantName();
                
                currentOrdersModel.addRow(row);
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentOrdersHeaderjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        currentOrdersjTable = new javax.swing.JTable();
        currentOrdersHeaderjLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveredOrdersjTable = new javax.swing.JTable();
        btnDelivered = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        feedbackjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ratingjComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));

        currentOrdersHeaderjLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        currentOrdersHeaderjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentOrdersHeaderjLabel.setText("Orders Assigned To Me");

        currentOrdersjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial-No", "CustomerName", "SpecialRequests", "Total Price", "Status", "AssignedBy", "Restaurant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        currentOrdersjTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(currentOrdersjTable);
        if (currentOrdersjTable.getColumnModel().getColumnCount() > 0) {
            currentOrdersjTable.getColumnModel().getColumn(0).setPreferredWidth(4);
        }

        currentOrdersHeaderjLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        currentOrdersHeaderjLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentOrdersHeaderjLabel1.setText("Orders Delivered By Me");

        deliveredOrdersjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial-No", "CustomerName", "SpecialRequests", "Total Price", "Status", "AssignedBy", "Restaurant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        deliveredOrdersjTable.getTableHeader().setReorderingAllowed(false);
        deliveredOrdersjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveredOrdersjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(deliveredOrdersjTable);
        if (deliveredOrdersjTable.getColumnModel().getColumnCount() > 0) {
            deliveredOrdersjTable.getColumnModel().getColumn(0).setPreferredWidth(4);
        }

        btnDelivered.setText("Delivered");
        btnDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveredActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Feedback :");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Rating :");

        ratingjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        ratingjComboBox.setSelectedIndex(4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(currentOrdersHeaderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(currentOrdersHeaderjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(feedbackjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ratingjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelivered))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(currentOrdersHeaderjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelivered)
                    .addComponent(jLabel1)
                    .addComponent(feedbackjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ratingjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(currentOrdersHeaderjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveredOrdersjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveredOrdersjTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveredOrdersjTableMouseClicked

    private void btnDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveredActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = currentOrdersjTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(this, "Please select a row to update delivery");
            return;
        }
        
        DefaultTableModel currentOrdersModel = (DefaultTableModel) currentOrdersjTable.getModel();
        Order order = (Order) currentOrdersModel.getValueAt(selectedRow, 3);
        order.setDeliveryPersonCustomerRating(ratingjComboBox.getSelectedIndex()+1);
        order.setDeliveryPersonFeedback(feedbackjTextField.getText());
        order.setOrderStatus(OrderStatus.Delivered);
        order.setLastUpdatedDate(new Date());
        order.setModifiedBy(userAccount.getName());
        populateData();
    }//GEN-LAST:event_btnDeliveredActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelivered;
    private javax.swing.JLabel currentOrdersHeaderjLabel;
    private javax.swing.JLabel currentOrdersHeaderjLabel1;
    private javax.swing.JTable currentOrdersjTable;
    private javax.swing.JTable deliveredOrdersjTable;
    private javax.swing.JTextField feedbackjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> ratingjComboBox;
    // End of variables declaration//GEN-END:variables
}
