

package userinterface.RestaurantAdminRole;


import Business.CityNetwork;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class RestaurantAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    UserAccount userAccount;
    Restaurant restaurant;
    CityNetwork cityNetwork;
    
    /** Creates new form AdminWorkAreaJPanel */
    public RestaurantAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, UserAccount userLogged,
        Restaurant restaurant, CityNetwork cityNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userLogged;
        this.restaurant = restaurant;
        this.cityNetwork = cityNetwork;
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageRestaurant = new javax.swing.JButton();
        btnManageOrder = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Restaurant");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 380, -1));

        btnManageRestaurant.setText("Manage Restaurant");
        btnManageRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRestaurantActionPerformed(evt);
            }
        });
        add(btnManageRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 180, -1));

        btnManageOrder.setText("Manage menu");
        btnManageOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrderActionPerformed(evt);
            }
        });
        add(btnManageOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 150, -1));

        btnManage.setText("Manage Orders");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRestaurantActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("UpdateRestaurantInfo", new UpdateRestaurantInfoJPanel(userProcessContainer, restaurant,userAccount));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRestaurantActionPerformed

    private void btnManageOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrderActionPerformed

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageMenuItems",new ManageMenuItemJPanel(userProcessContainer, userAccount, restaurant));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrderActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageOrdersPanel", new ManageOrdersRestaurantJPanel(userProcessContainer, userAccount, restaurant,
            ecoSystem, cityNetwork));
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageActionPerformed
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnManageOrder;
    private javax.swing.JButton btnManageRestaurant;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
